### ISSUE TITLE
Bracketing issue with multiple conjuncts

### ISSUE THREAD

**Issue by k-ghoshal** [nyusemantics/LambdaCalculator-Issues#28]
The lambda calculator is overly strict with bracketing, making it so that when there are more than two conjuncts: bracketing must be done in the exact order in which things were substituted in. The issue arises in question 4 in the attached exercise file, for instance. 
The only accepted response is: ∃x.[Diplomat(x) ∧ [∀y.[Country(y) → [∃e.[Visit(e) ∧ [[true ∧ [agent(e) = x]] ∧ [theme(e) = y]]]]]]]
which is a somewhat non-intuitive bracketing. For example, another response that should also be accepted is:
∃x.[Diplomat(x) ∧ [∀y.[Country(y) → [∃e.[Visit(e) ∧ [true ∧ [[agent(e) = x] ∧ [theme(e) = y]]]]]]]]
The lambda calculator removes the brackets at every step so one has to manually put them back in the "correct" configuration (i.e. following the substitution order). It is possible that if it is not given explicit bracketing, the calculator is applying a default bracketing starting with grouping the rightmost elements together and that does not work in this case because it does not match the substition order (should be checked whether this is true). Another issue is that it should be possible to drop the 'true' but that seems like an unrelated thing.

I think the issue comes down to two things:
1) it cannot handle triple conjuncts, so one must make sure the bracketing ensures this, even though it keeps removing the brackets when you apply a rule so you have to put them back manually
2) when substituting something like f(e) for say, [f(e) & [agent(e)=x]], one must make sure these two things remain bracketed together in the simplified expression at every subsequent step. So if you substitute this value for f(e) into
[Visit(e) & [f(e) & [th(e)=m]]],  one needs to simplify this to
[Visit(e) & [[f(e) & [agent(e)=j]] & [th(e)=m]]] and NOT
[Visit(e) & [f(e) & [[agent(e)=j] & [th(e)=m]]]]
Since it keeps removing the brackets at every step, one needs to put back the brackets exactly how they were and make sure this bracketing is followed till the end.
So one gets weird non-intuitive bracketing like 1&[[2&3]&4], whereas since it removes the brackets one would try to bracket it like 1&[2&[3&4]], even though these are logically equivalent.

Following the rules I explained above strictly, I was able to fully simplify all the exercises in this file successfully; even though the resulting bracketing looks a little odd to the eye, it makes sense according to the calculator's logic.

[ps10-intsem-2021.txt](https://github.com/nyusemantics/LambdaCalculatorPublic/files/8835845/ps10-intsem-2021.txt)

**Comment by RTKno1** [comment]
This issue has been resolved as of version 2.6.0.
