### ISSUE TITLE
Can't install on Mac with M1 chip and Ventura

### ISSUE THREAD

**Issue by dwbcampbell** [nyusemantics/LambdaCalculator-Issues#31]
I tried opening the DMG on my laptop and it doesn't do anything. My laptop has an Apple M1 chip and is running Ventura 13.5.1

**Comment by champoll** [comment]
Thanks for letting us know! We haven't tested on Ventura and M1 yet. Try right-clicking on the dmg and selecting Open. If that doesn't work, could you open Terminal and include the output of the following commands?

hdiutil attach -debug /path/to/Lambda_Calculator_SE_Mac_2.6.0.dmg
hdiutil attach -verbose /path/to/Lambda_Calculator_SE_Mac_2.6.0.dmg

**Comment by dwbcampbell** [comment]
Thanks for your quick response. Here are the logs.  But I didn't realize the mount had succeeded -- I didn't think to look in the finder and was expecting a popup -- and from there I was able to install the app and it works. 
[dmg.debug.log](https://github.com/nyusemantics/LambdaCalculatorPublic/files/12849906/dmg.debug.log)
[dmg.verbose.log](https://github.com/nyusemantics/LambdaCalculatorPublic/files/12849909/dmg.verbose.log)

**Comment by champoll** [comment]
Oh, so in that case there's no issue. I'm glad to hear it works!
